name: Deploy via ftp
on:
  push:
    branches:
      - main  # ou a branch que você usa para deploy, como 'master'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"
          remoteDir: "public_html"  # Use 'web' se for uma hospedagem Windows
          forceSsl: true
